### ISSUE TITLE
InvalidParameterValue: Missing local name

### ISSUE THREAD

**Issue by stuartford** [arithmetric/aws-lambda-ses-forwarder#103]
So close with this, but it's throwing this error which I cannot find anything about on Google. It doesn't even seem to be related to anything in the AWS docs (https://docs.aws.amazon.com/ses/latest/APIReference/API_SendRawEmail.html)

The message immediately before this error suggests that both the original recipients and the transformed recipients have been parsed correctly.

How do I fix this?

> 2018-12-16T14:15:01.413Z	884eecec-013c-11e9-9918-4d49de041ed2	{ level: 'error',
message: 'sendRawEmail() returned error.',
error: 
{ InvalidParameterValue: Missing local name
at Request.extractError (/var/task/node_modules/aws-sdk/lib/protocol/query.js:40:29)
at Request.callListeners (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
at Request.emit (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
at Request.emit (/var/task/node_modules/aws-sdk/lib/request.js:615:14)
at Request.transition (/var/task/node_modules/aws-sdk/lib/request.js:22:10)
at AcceptorStateMachine.runTo (/var/task/node_modules/aws-sdk/lib/state_machine.js:14:12)
at /var/task/node_modules/aws-sdk/lib/state_machine.js:26:10
at Request.<anonymous> (/var/task/node_modules/aws-sdk/lib/request.js:38:9)
at Request.<anonymous> (/var/task/node_modules/aws-sdk/lib/request.js:617:12)
at Request.callListeners (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
message: 'Missing local name',
code: 'InvalidParameterValue',
time: 2018-12-16T14:15:01.413Z,
requestId: 'f9e3eb70-013c-11e9-8c63-3b422254ac74',
statusCode: 400,
retryable: false,
retryDelay: 76.30022950087816 },
stack: 'InvalidParameterValue: Missing local name\n at Request.extractError (/var/task/node_modules/aws-sdk/lib/protocol/query.js:40:29)\n at Request.callListeners (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:105:20)\n at Request.emit (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:77:10)\n at Request.emit (/var/task/node_modules/aws-sdk/lib/request.js:615:14)\n at Request.transition (/var/task/node_modules/aws-sdk/lib/request.js:22:10)\n at AcceptorStateMachine.runTo (/var/task/node_modules/aws-sdk/lib/state_machine.js:14:12)\n at /var/task/node_modules/aws-sdk/lib/state_machine.js:26:10\n at Request.<anonymous> (/var/task/node_modules/aws-sdk/lib/request.js:38:9)\n at Request.<anonymous> (/var/task/node_modules/aws-sdk/lib/request.js:617:12)\n at Request.callListeners (/var/task/node_modules/aws-sdk/lib/sequential_executor.js:115:18)' }

**Comment by aroravicky** [comment]
HI,

Any update on this issue as i am getting the same error while implementing arithmetric email forwarding solution

**Comment by kevbarns** [comment]
Same issue here.. It's related to the fromEmail of the config object.

**Comment by andreguilhon** [comment]
I was also getting this error, not from this repository exactly, but this was the only place I found the error. I found out I was sending the recipients field as a string, while it should be a list. Don't know if this can help you, but it worked for me.
Also, other answers from similar errors led me to this page https://mg.pov.lt/blog/unicode-emails-in-python.html which maybe can also help you.
