### ISSUE TITLE
node 18.x support

### ISSUE THREAD

**Issue by clarson** [arithmetric/aws-lambda-ses-forwarder#144]
Hi,

This script does not work when lambda is configured to run node 18.   AWS lambda node 18 is using AWS SDK v3 and the require statement no longer works.

More information here:
https://aws.amazon.com/blogs/compute/node-js-18-x-runtime-now-available-in-aws-lambda/

Thanks,
Chuck

**Comment by ellis-sutehall** [comment]
I'm having the same problem. I had to update my script and SES forced my to upgrade the node version and now it doesn't work.

Were you able to fix it?

**Comment by clarson** [comment]
I was able to go back to node 16 which is still supported.   I just checked before this reply.

**Comment by dekkeravesque** [comment]
Node 16 is giving me the same error! I read elsewhere that I could add the following code to fix the require statement, which did make that error go away, but I am now seeing a reference error: "exports not defined in ES module scope"... Is Node 16 actually supported? I tried Node 14 as well, since Node 12 is no longer available on AWS, and had the exact same results.

code to fix require statement:

import { createRequire } from 'module';
const require = createRequire(import.meta.url);

new error:

2023-08-23T20:28:22.810Z	undefined	ERROR	Uncaught Exception 	
{
    "errorType": "ReferenceError",
    "errorMessage": "exports is not defined in ES module scope",
    "stack": [
        "ReferenceError: exports is not defined in ES module scope",
        "    at file:///var/task/index.mjs:71:1",
        "    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)",
        "    at async Promise.all (index 0)",
        "    at async ESMLoader.import (node:internal/modules/esm/loader:530:24)",
        "    at async _tryAwaitImport (file:///var/runtime/index.mjs:918:16)",
        "    at async _tryRequire (file:///var/runtime/index.mjs:967:86)",
        "    at async _loadUserApp (file:///var/runtime/index.mjs:991:16)",
        "    at async Object.UserFunction.js.module.exports.load (file:///var/runtime/index.mjs:1029:21)",
        "    at async start (file:///var/runtime/index.mjs:1192:23)",
        "    at async file:///var/runtime/index.mjs:1198:1"
    ]
}

**Comment by dekkeravesque** [comment]
I am also getting this issue, and Node 16 doesn't seem to have require support. As I am reading, all versions above 12 do not support require.

I added the following, which fixed the require error, but was still getting an error about exports not being defiined in ES module scope:

import { createRequire } from 'module';
const require = createRequire(import.meta.url);

Then I noticed issue 146 which supposedly fixes, so I used the code from that commit, but it still uses require, so it still threw the require error. I added the above code to fix the require error, and still get the same error about exports not being defined:

2023-08-23T21:59:52.408Z	undefined	ERROR	Uncaught Exception 	
{
    "errorType": "ReferenceError",
    "errorMessage": "exports is not defined in ES module scope",
    "stack": [
        "ReferenceError: exports is not defined in ES module scope",
        "    at file:///var/task/index.mjs:80:1",
        "    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)"
    ]
}

Any chance anyone can help me, or can explain how #146 is supposed to fix this?

**Comment by dekkeravesque** [comment]
So, it would seem the issue here is actually that folks encountering this problem are using the ECMA Script Module system instead of CommonJS, as Node 18 actually _does_ support require... It is ES Modules that do not support require: https://nodejs.org/api/esm.html#no-require-exports-or-moduleexports

By default the index handler created in AWS has the extension .mjs, but you can change it to .cjs to run CommonJS instead. You will still run into the issue of needing to use AWS SDK v3, however, which lpsinger has implemented in #146.

**Comment by mylesboone** [comment]
Here's code that will run on Node 18.x and uses SES v1 client:

https://gist.github.com/mylesboone/b6113f8dd74617d27f54e5d0b8598ff7

**Comment by Minjun-KANG** [comment]
> Here's code that will run on Node 18.x and uses SES v1 client:
> 
> https://gist.github.com/mylesboone/b6113f8dd74617d27f54e5d0b8598ff7

error: PermanentRedirect: The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint.

You may encounter the above error message.
In this case, you can set the region in S3 as shown below.
Thank you for sharing the code.

s3: overrides && overrides.s3 ?
      overrides.s3 : new S3Client({signatureVersion: 'v4', region: 'ap-northeast-2'})

**Comment by arithmetric** [comment]
Thanks for this report! I've updated the documenation to recommend using the Node.js 16 runtime for now: https://github.com/arithmetric/aws-lambda-ses-forwarder/commit/67bc86b44823099c838a82a499ff095d508737a8

However I also found that the code works in Node.js 18 as is if you install the AWS SDK v2 module and its dependencies.

To do this, change the following step in the documented Set Up process:

> For the Lambda function code, either copy and paste the contents of index.js into the inline code editor or zip the contents of the repository and upload them directly or via S3.

To do the following instead:

1. In a copy of this repository, run `npm i --omit=dev`
2. Create a `.zip` file with the contents of this repository. Note: `index.js` should be at the root of the zip file and not in a directory.
3. Upload the zip file to Lambda.

Let me know if this approach works for you.

**Comment by lvn1** [comment]
> Here's code that will run on Node 18.x and uses SES v1 client:
> 
> https://gist.github.com/mylesboone/b6113f8dd74617d27f54e5d0b8598ff7

I managed to get it working in Node.js 18 by modifying the gist and only using the lambda code editor, without installing any additional dependencies.

CloudWatch errors were showing: 
- _require is not defined in ES module scope, you can use import instead_  
- _exports is not defined in ES module scope_

I just updated the import statements, changed the 5 exports to consts and changed the exports.handler to export const handler.

https://gist.github.com/lvn1/9814d301bead8e0ecfc79ba9efe64b4a

**Comment by hacnet** [comment]
> > Here's code that will run on Node 18.x and uses SES v1 client:
> > https://gist.github.com/mylesboone/b6113f8dd74617d27f54e5d0b8598ff7
> 
> I managed to get it working in Node.js 18 by modifying the gist and only using the lambda code editor, without installing any additional dependencies.
> 
> CloudWatch errors were showing:
> 
> * _require is not defined in ES module scope, you can use import instead_
> * _exports is not defined in ES module scope_
> 
> I just updated the import statements, changed the 5 exports to consts and changed the exports.handler to export const handler.
> 
> https://gist.github.com/lvn1/9814d301bead8e0ecfc79ba9efe64b4a

The 2nd gist presumably needs to have line 3-4 replaced with that of the 1st link.

It then still fails where `export const handler` is unexpected and/or related steps need further modification.

**Comment by mylesboone** [comment]
@hacnet I'd suggest using https://github.com/arithmetric/aws-lambda-ses-forwarder/pull/147

**Comment by hacnet** [comment]
> @hacnet I'd suggest using #147

That fixed it, many thanks!
