### ISSUE TITLE
Could not make readable copy of email

### ISSUE THREAD

**Issue by mvasin** [arithmetric/aws-lambda-ses-forwarder#42]
I double-checked all the permissions according to readme, but still get the error:

```
START RequestId: af224ff3-fb47-11e6-9444-1f9e512246cc Version: $LATEST
2017-02-25T10:46:38.924Z	af224ff3-fb47-11e6-9444-1f9e512246cc	{ level: 'info',
  message: 'Fetching email at s3://musweb.mail/o3vrnil0e2ic28trm7dfhrc2v0clambda4nbp0g1' }
2017-02-25T10:46:40.344Z	af224ff3-fb47-11e6-9444-1f9e512246cc	{ level: 'error',
  message: 'copyObject() returned error:',
  error: 
   { [AccessDenied: Access Denied]
     message: 'Access Denied',
     code: 'AccessDenied',
     region: null,
     time: Sat Feb 25 2017 10:46:40 GMT+0000 (UTC),
     requestId: '4CC93788EF0116A6',
     extendedRequestId: 'nGtVxfT3aT/uqPpufrdvjJrLy/ClZ4WeJoqh8AK9eXy5keqqx3Q89SSnkrvIYyxnSS31STpGF00=',
     cfId: undefined,
     statusCode: 403,
     retryable: false,
     retryDelay: 50.05418912041932 },
  stack: 'AccessDenied: Access Denied
    at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/services/s3.js:538:35)
    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:671:14)
    at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:673:12)
    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:115:18)' }
2017-02-25T10:46:40.404Z	af224ff3-fb47-11e6-9444-1f9e512246cc	{ level: 'error',
  message: 'Step returned error: Error: Could not make readable copy of email.',
  error: [Error: Error: Could not make readable copy of email.],
  stack: 'Error: Error: Could not make readable copy of email.
    at Response.<anonymous> (/var/task/index.js:145:11)
    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:358:18)
    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:671:14)
    at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:673:12)' }
2017-02-25T10:46:40.405Z	af224ff3-fb47-11e6-9444-1f9e512246cc	{"errorMessage":"Error: Step returned error.","errorType":"Error","stackTrace":["/var/task/index.js:302:28","process._tickDomainCallback (node.js:407:9)"]}
END RequestId: af224ff3-fb47-11e6-9444-1f9e512246cc
REPORT RequestId: af224ff3-fb47-11e6-9444-1f9e512246cc	Duration: 1942.54 ms	Billed Duration: 2000 ms 
```

**Comment by jakubboucek** [comment]
Step 1: Open your [**Lambda** function](https://console.aws.amazon.com/lambda/home), switch to **Configuration** tab and check Role name (in **Existing role** field.
Step 2: Open IAM, select [Roles](https://console.aws.amazon.com/iam/home#/roles) in menu and open the role used in Lambda.
Step 3: Check if is attached any Policy with required access do S3 bucket, for example:
```JSON
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "logs:CreateLogGroup",
                "logs:CreateLogStream",
                "logs:PutLogEvents"
            ],
            "Resource": "arn:aws:logs:*:*:*"
        },
        {
            "Effect": "Allow",
            "Action": "ses:SendRawEmail",
            "Resource": "*"
        },
        {
            "Effect": "Allow",
            "Action": [
                "s3:GetObject",
                "s3:PutObject"
            ],
            "Resource": "arn:aws:s3:::musweb.mail/*"
        }
    ]
}
```

**Comment by mvasin** [comment]
Thanks for the reply. Unfortunately, that's exactly what I already had, so it didn't help.

But when I attached AmazonS3FullAccess policy to the Lambda, it gave me another error:

```
START RequestId: df166a9c-fd83-11e6-a621-9980f679e7bc Version: $LATEST
2017-02-28T07:02:30.696Z	df166a9c-fd83-11e6-a621-9980f679e7bc	{ level: 'info',
  message: 'Fetching email at s3://musweb.mail/o3vrnil0e2ic28trm7dfhrc2v0clambda4nbp0g1' }
2017-02-28T07:02:30.937Z	df166a9c-fd83-11e6-a621-9980f679e7bc	{ level: 'error',
  message: 'copyObject() returned error:',
  error: 
   { [NoSuchKey: The specified key does not exist.]
     message: 'The specified key does not exist.',
     code: 'NoSuchKey',
     region: null,
     time: Tue Feb 28 2017 07:02:30 GMT+0000 (UTC),
     requestId: '800124704E92714F',
     extendedRequestId: 'IRJTfV2Tf/FOf4OAN/HSzx6CZrWwDPJF9A3dtWPJTPwewrNsVBkyLBaWs+vjbijvMpusPO5MClA=',
     cfId: undefined,
     statusCode: 404,
     retryable: false,
     retryDelay: 84.66746141202748 },
  stack: 'NoSuchKey: The specified key does not exist.
    at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/services/s3.js:538:35)
    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:671:14)
    at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:673:12)
    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:115:18)' }
2017-02-28T07:02:30.937Z	df166a9c-fd83-11e6-a621-9980f679e7bc	{ level: 'error',
  message: 'Step returned error: Error: Could not make readable copy of email.',
  error: [Error: Error: Could not make readable copy of email.],
  stack: 'Error: Error: Could not make readable copy of email.
    at Response.<anonymous> (/var/task/index.js:145:11)
    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:358:18)
    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:671:14)
    at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:673:12)' }
2017-02-28T07:02:30.938Z	df166a9c-fd83-11e6-a621-9980f679e7bc	{"errorMessage":"Error: Step returned error.","errorType":"Error","stackTrace":["/var/task/index.js:302:28","process._tickDomainCallback (node.js:407:9)"]}
END RequestId: df166a9c-fd83-11e6-a621-9980f679e7bc
REPORT RequestId: df166a9c-fd83-11e6-a621-9980f679e7bc	Duration: 247.91 ms	Billed Duration: 300 ms 	Memory Size: 128 MB	Max Memory Used: 31 MB	
```

**Comment by jakubboucek** [comment]
That's look better now. You have access to S3 now, but object in S3 is doesn't exist. 

Are you sure you have setted SES rule to put mail to S3 in `musweb.mail` bucket without `Object key prefix`? 

Is for me very confusing you have same mail object S3 key in both of pasted logs (`s3://musweb.mail/o3vrnil0e2ic28trm7dfhrc2v0clambda4nbp0g1`). Is that Lambda handler really called from SES or is it launched by Test?

**Comment by mvasin** [comment]
Yes, that's a test event, that's why it has the same id. I just replaced 'example.com' with 'infomed.moscow' in the default SES Email receiving test.

I had an empty string for prefix both in index.js and SES config, now I tried 'test/' prefix in `index.js`'s `DefaultConfig` object, and both 'test' and 'test/' in SES rule.

Then I once again carefully went through all of the readme. And nothing helped.

I noticed that having 'test' as `Object key prefix` in SES' rule setting does not create a test folder when I send a mail to noreply@infomed.moscow. It saves a mail to bucket's root folder. Should I see 'test' as a filename prefix for bucket object? I don't see it prepended.

The 'test/' prefix does create a folder 'test' with AMAZON_SES_SETUP_NOTIFICATION file in the bucket (right after saving the setting, before any mail received), but the incoming mails are still saved to root.

I tried removing the Lambda action in the SES rule to make it save into the prefix folder (AMAZON_SES_SETUP_NOTIFICATION says "the rule... is only valid if the entire setup process is successful"), but it didn't help.

So maybe being not able to save a mail into a prefix folder is the key to the problem? But I have no idea how to fix it.

**Comment by jakubboucek** [comment]
This forwarder script is not fully compatible with default SES Email receiving test, because it not create the required object in S3.

You can keep `Object key prefix` empty, i just asked if you have same prefix set on both sites. But It does not matter when you used only test event.

When is `AMAZON_SES_SETUP_NOTIFICATION` created without error, that should been saved and active. Did you have not more concurrent SES Rules? Or more Rule Sets? Did you tried it yesterday when AWS was outage with S3 (and more services was affected, SES including)? Please try it again.

**Comment by mvasin** [comment]
Is it hard to make it compatible with the default SES Email test or provide your test script? It would clear out so much confusion.

I have one ruleset with one rule inside with two actions: S3 and then Lambda (SesForwarder).

I tried it a few hours ago and retried now. The same.

**Comment by mvasin** [comment]
Thank you so much for the Hangouts session, Jakub! The biggest problem seemed to be confusing interface of rule sets in SES. I was sure I had one rule, but it happened to be 1) inactive 2) there happened to be another rule.

**Comment by jakubboucek** [comment]
… 3) and missing required policy for Lambda's Role. :)

**Comment by jhabdas** [comment]
What's the purpose of `logs:CreateLogGroup` in the policy document provided? I had AWS automatically create my policy document for me and it left that off, and forwarding still works.

**Comment by jakubboucek** [comment]
@jhabdas `logs:CreateLogGroup` is not necessary for forwarding. But it is important to present in policy because it allows save logs. You need logs when cause any problem.

**Comment by george-viaud** [comment]
To anyone having what appears to be S3 access errors, make sure your prefix matches.  I just spent quite a bit of time trying to debug an S3 access issue due to a typo in my prefix when setting up lambda (doh).  This thread helped me a lot in discovering this - thank you.
