### ISSUE TITLE
TypeError: Cannot read property 'log' of undefined

### ISSUE THREAD

**Issue by spolspol** [arithmetric/aws-lambda-ses-forwarder#71]
Getting this error:

017-12-01T13:23:19.809Z	cbb36a51-d69a-11e7-966a-e777dc99be75	{ level: 'error',
message: 'Step returned error: Cannot read property \'log\' of undefined',
error: 
TypeError: Cannot read property 'log' of undefined
at exports.fetchMessage (/var/task/index.js:127:7),
stack: 'TypeError: Cannot read property \'log\' of undefined\n at exports.fetchMessage (/var/task/index.js:127:7)' }

**Comment by spolspol** [comment]
OK it was just me trying to forward on the whole domain missing an @ in "@example.com" in the mapping.

**Comment by rasmuscnielsen** [comment]
Thanks - encountered a similar error. Forgot to change 'example.com' to my own domain. 

In short: this error occurs when the actual email recipient can't be matched to the expected recipients in the mapping.
